#!/usr/bin/env bash

set -e

SCRIPTDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOTDIR="$(cd "${SCRIPTDIR}/.." && pwd)"

set -x

# Check if there are any commits
if git -C "$ROOTDIR" rev-parse --quiet --verify HEAD; then
  # Generate AUTHORS file with contributors
  cat > "${ROOTDIR}/AUTHORS" <<- EOF
    # File @generated by generate-authors.sh. DO NOT EDIT.
    # This file lists all contributors to the repository.
    # See generate-authors.sh to make modifications.

    $(git -C "$ROOTDIR" log --format='%aN <%aE>' | LC_ALL=C.UTF-8 sort -uf)
EOF
else
  # If no commits, create an empty AUTHORS file
  echo "# No contributors yet." > "${ROOTDIR}/AUTHORS"
fi
